# Generated by Django 5.0.2 on 2025-05-26 20:25

from django.db import migrations

def add_travel_options(apps, schema_editor):
    TravelPurpose = apps.get_model('travel_input', 'TravelPurpose')
    TravelStyle = apps.get_model('travel_input', 'TravelStyle')
    ImportantFactor = apps.get_model('travel_input', 'ImportantFactor')

    # Add Travel Purposes
    purposes = [
        '휴식', '관광', '액티비티', '미식', '쇼핑',
        '문화탐방', '자연체험', '역사탐방', '힐링', '업무',
    ]
    for purpose_name in purposes:
        TravelPurpose.objects.get_or_create(name=purpose_name)

    # Add Travel Styles
    styles = [
        '혼자', '친구와', '연인과', '가족과', '단체',
        '계획적', '즉흥적', '럭셔리', '가성비', '편안한',
    ]
    for style_name in styles:
        TravelStyle.objects.get_or_create(name=style_name)

    # Add Important Factors
    factors = [
        '숙소', '음식', '교통', '비용', '시간',
        '날씨', '치안', '언어', '액티비티', '문화체험',
    ]
    for factor_name in factors:
        ImportantFactor.objects.get_or_create(name=factor_name)

class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0020_add_default_destinations'),
    ]

    operations = [
        migrations.RunPython(add_travel_options),
    ]
