# Generated by Django 5.0.2 on 2025-05-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0021_add_initial_travel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
    ]
