# Generated by Django 5.0.2 on 2025-05-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0022_remove_city_slug_alter_city_is_active'),
        ('travel_input', '0022_remove_city_slug_schedule_travel_tips_and_more'),
    ]

    operations = [
    ]
