# Generated by Django 5.0.2 on 2025-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0023_merge_20250527_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='travel_tips',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 개전 제안'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='season',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='희망 계절'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='사용자 피드립'),
        ),
        migrations.DeleteModel(
            name='RecommendedPlace',
        ),
    ]
