# Generated by Django 5.2.1 on 2025-05-28 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0024_remove_schedule_travel_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='travel_tips',
            field=models.TextField(blank=True, null=True, verbose_name='여행 준비 팁'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 개선 제안'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='season',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='휴가 계절'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='사용자 피드백'),
        ),
        migrations.CreateModel(
            name='RecommendedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='장소명')),
                ('description', models.TextField(verbose_name='설명')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('map_url', models.URLField(blank=True, null=True, verbose_name='지도 URL')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_places', to='travel_input.schedule')),
            ],
            options={
                'verbose_name': '추천 장소',
                'verbose_name_plural': '추천 장소들',
                'ordering': ['order', 'name'],
            },
        ),
    ]
