# Generated by Django 5.2.1 on 2025-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0025_schedule_travel_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='daily_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='meal_places',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='qa_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='transportation_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='important_factors',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='travel_input.importantfactor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
