# Generated by Django 5.2.1 on 2025-05-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0026_schedule_daily_schedule_schedule_meal_places_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='daily_schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='meal_places',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='qa_history',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='transportation_details',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 개선 제안'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 생성 결과'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='important_factors',
            field=models.ManyToManyField(blank=True, to='travel_input.importantfactor', verbose_name='중요 요소'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='사용자 피드백'),
        ),
    ]
