# Generated by Django 5.2.1 on 2025-05-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0027_remove_schedule_daily_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='qa_history',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Q&A 기록'),
        ),
    ]
