# Generated by Django 5.2.1 on 2025-05-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0028_schedule_qa_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='종료 시간'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='시작 시간'),
        ),
    ]
