# Generated by Django 5.2.1 on 2025-05-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0029_schedule_end_time_schedule_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_schedules', to='travel_input.city', verbose_name='출발지'),
        ),
    ]
